### ISSUE TITLE
winmm.dll support 

### ISSUE THREAD

**Issue by SAM1430B** [aap/simpledllloader#1]
Hello, is there way to load winmm.dll
I tried to add it in dlls.cfg but seems it doesn't load.

**Comment by aap** [comment]
that's just a filename. it depends on the actual file whether it can be loaded or does anything. i noticed on windows 10 that a dll that fails to load (e.g. because msvc redist is missing) gives no error message but the dll is simply unloaded. that's not at all very helpful.

**Comment by SAM1430B** [comment]
I've found alternative way to load winmm.dll, sad thing Microsoft never fix it.
https://github.com/YELLO-belly/ogg-winmm/tree/master/PS-Script
